# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

workflows:
  version: 2

  # base workflow
  # See: https://ideas.circleci.com/ideas/CCI-I-627
  on_commit: &on_commit
    jobs:
      # - backup_docs
      - update_shortlinks:
        filters:
          branches:
            only: master

  # scheduled workflow
  nightly:
    <<: *on_commit
    triggers:
      - schedule:
          # Every night at 4am ET
          cron: "0 9 * * *"
          filters:
            branches:
              only: master


version: 2

jobs:
  default: &default_job
    docker:
      - image: circleci/python:3.6.6
      # For the following sensitive envvars, check the CircleCI UI.
      #   - GITHUB_API_TOKEN
      #
      # See: https://circleci.com/gh/cryptographydog/worker-coop-scripts/edit#env-vars
    steps:
      - checkout

      - run: &decrypt_files
          name: decrypt files
          command: |
            true
            # Uncomment if key files needed.
            #openssl aes-256-cbc -k "$DECRYPTION_SECRET" -in service-key.json.enc -out service-key.json -d

      - restore_cache: &restore_cache
          keys:
          - cache-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - cache-

      - run: &install_dependencies
          name: install dependencies
          command: |
            pipenv sync --dev

      - save_cache: &save_cache
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

  backup_docs:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            pipenv run python cli.py backup2github \
              --github-token "$GITHUB_API_TOKEN" \
              --github-repo "$CIRCLE_PROJECT_USERNAME/december-retreat" \
              --resource-list "examples/files-to-backup.csv"

  update_shortlinks:
    <<: *default_job
    steps:
      - checkout
      - run: {<<: *decrypt_files}
      - restore_cache: {<<: *restore_cache}
      - run: {<<: *install_dependencies}
      - save_cache: {<<: *save_cache}
      - run:
          name: run script
          command: |
            pipenv run spreadsheet2shortlinks --yes --verbose \
              --gsheet "https://docs.google.com/spreadsheets/d/1DpnzCpXWgQr66nFJFIlpa5XSBrt8IfZaLVZH0_q6kcA/edit#gid=0" \
              --domain-name "link.hypha.coop" \
              --rebrandly-api-key "$REBRANDLY_API_KEY"
